Args = --initialize-at-build-time \
       --no-fallback \
       --report-unsupported-elements-at-runtime \
       -H:+ReportExceptionStackTraces \
       --enable-http \
       --enable-https \
       -H:Log=registerResource:3
