repos:
  - repo: local
    hooks:
      - id: cljfmt-check
        name: cljfmt (Clojure formatter check)
        entry: bb format:check
        language: system
        files: \.clj$
        pass_filenames: false

      - id: clj-kondo
        name: clj-kondo (Clojure linter)
        entry: bb lint
        language: system
        files: \.clj$
        pass_filenames: false

      - id: clj-tests
        name: Clojure tests
        entry: bb test
        language: system
        files: \.clj$
        pass_filenames: false
