apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ark-discord-bot-github-secret
  namespace: ark-discord-bot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: ark-discord-bot-github-secret
    creationPolicy: Owner
  data:
  - secretKey: GITHUB_TOKEN
    remoteRef:
      key: /ark-discord-bot/github-token
