apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- rbac.yaml
- deployment.yaml

images:
- name: ark-discord-bot
  newTag: latest

commonLabels:
  app: ark-discord-bot
  version: v1.0.0

namespace: ark-discord-bot