apiVersion: v1
kind: Namespace
metadata:
  name: ark-discord-bot
  labels:
    name: ark-discord-bot
    app.kubernetes.io/name: ark-discord-bot
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: discord-bot